# Generated by Django 2.0.6 on 2019-07-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='login',
            name='mobile',
            field=models.CharField(default='', max_length=10),
        ),
    ]
